# Generated by Django 5.0.3 on 2024-03-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='Botao',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='LigaRobo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='ResetContador',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='Sensor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='Valor_Contagem',
            field=models.IntegerField(),
        ),
    ]
